### ISSUE TITLE
`thrust::async::copy(thrust::device.after(thing), ...)` fails with a `no_state` exception because the policy is copied twice and then moved from twice

### ISSUE THREAD

**Issue by jeng1220** [thrust/thrust#1115] opened 2020-04-21 02:15 UTC
The original report is #651, but the fix to the issue has been lost. The internal nvbug is 200501674. 

I also tried new Thrust API with CUDA 10.2 but it still crashed.
```c++
#include <thrust/host_vector.h>
#include <thrust/device_vector.h>
#include <thrust/async/copy.h>

int main()
{
  int N = 5000;
  thrust::host_vector<float> a(N);
  thrust::device_vector<float> b(N);
  thrust::device_event e(thrust::new_stream);
  e = thrust::async::copy(thrust::device.after(e), a.begin(), a.end(), b.begin());
  e.wait();
  return 0;
}
```
Even doing D2D memcpy encountered same error:
```c++
#include <thrust/device_vector.h>
#include <thrust/async/copy.h>

int main()
{
  int N = 5000;
  thrust::device_vector<float> a(N);
  thrust::device_vector<float> b(N);
  thrust::device_event e(thrust::new_stream);
  e = thrust::async::copy(thrust::device.after(e), a.begin(), a.end(), b.begin());
  e.wait();
  return 0;
}
```
The error message is:
```sh
terminate called after throwing an instance of 'thrust::event_error'
  what():  no_state: an operation that requires an event or future to have a stream or content has been performed on a event or future without either, e.g. a moved-from or default constructed event or future (anevent or future may have been consumed more than once)
```

**Comment by jeng1220** [comment] 2020-04-21 02:21
add @jaredhoberock to increase visibility

**Comment by brycelelbach** [comment] 2020-05-01 03:27
This happens because the one-policy overload of `async::copy` copies its single policy argument and uses it as both the "to" and "from" policy when calling the two-policy overload of `async::copy`. This is problematic because the stream-stealing code in `thrust::future` extracts the stream from the event in the first copy of the policy, leaving the second copy in a moved-from state, leading to the `no_state`  exception.

My solution is to change the one-policy overload to assume its single policy argument is the "to" policy and infer the "from" policy from iterators (which is what is done for both policies in the no-policy overload). I think this is the best thing to do - the one-policy overload of copy has always been a little vague about what it means, since copy is the one operation in Thrust that can happen between hosts and devices.

**Comment by brycelelbach** [comment] 2020-05-01 03:54
> The original report is #651, but the fix to the issue has been lost. The internal nvbug is 200501674.

Can you elaborate on what you mean by this? #651 is a separate issue with the synchronous API. Are you seeing a regression for that issue?

**Comment by brycelelbach** [comment] 2020-05-01 03:55
> the one-policy overload of copy has always been a little vague about what it means,

Maybe we should just delete it for `async::copy`.

**Comment by brycelelbach** [comment] 2020-05-07 03:28
Okay, based on [this Twitter poll](https://twitter.com/blelbach/status/1256065185699098625), I've decided to not change the semantics here and just fix the single-policy overload to not copy. The fix is in flight.

However, that means your code will remain incorrect; you need to use the two-policy overload. The overload you are using says "assume that both the source and destination are accessible on the GPU".

So, TL;DR, there should be a fix in tomorrow which will ship with 1.9.10. But you need to update your code to:

```
#include <thrust/host_vector.h>
#include <thrust/device_vector.h>
#include <thrust/async/copy.h>

int main()
{
  int N = 5000;
  thrust::host_vector<float> a(N);
  thrust::device_vector<float> b(N);
  thrust::device_event e(thrust::new_stream);
  e = thrust::async::copy(thrust::host, thrust::device.after(e), a.begin(), a.end(), b.begin());
  e.wait();
  return 0;
}
```

**Comment by jeng1220** [comment] 2020-05-07 06:45
About H2D and D2H copy, using two-policy overload is acceptable. Although less convenient but more explicit.

However, a reminder that this bug also happens in the D2D copy case, for instance:
```c++
#include <thrust/device_vector.h>
#include <thrust/async/copy.h>

int main()
{
  int N = 5000;
  thrust::device_vector<float> a(N);
  thrust::device_vector<float> b(N);
  thrust::device_event e(thrust::new_stream);
  e = thrust::async::copy(thrust::device.after(e), a.begin(), a.end(), b.begin());
  e.wait();
  return 0;
}
```
Do you mean that even D2D copy needs to use two-policy overload after Thrust 1.9.10.?

**Comment by brycelelbach** [comment] 2020-05-07 07:03
Jeng,


Thanks - yes I know. There is a referenced PR associated with this issue that fixes the problem. It should be merged tomorrow.


For D2D you can use the one overload issue.

Sent from Nine<http://www.9folders.com/>
________________________________

**Closed** 2020-05-08 22:26 UTC

**Comment by brycelelbach** [comment] 2020-05-08 22:28
Fixed.
