### ISSUE TITLE
reduce_by_key fails with ' bulk_kernel_by_value: an illegal memory access was encountered' if element size is too big

### ISSUE THREAD

**Issue by dachziegel** [thrust/thrust#640] opened 2015-03-02 11:26 UTC
I came across a bug which is very similar to #483:

If the size of the element that should be reduced by key is too big, reduce_by_key fails with:

**bulk_kernel_by_value: an illegal memory access was encountered**

The same demo program as in #483 now fails **if ARRAY_SIZE is bigger than 7**:

https://gist.github.com/dachziegel/11288269

I compiled it using
nvcc -arch sm_20 -DTHRUST_DEBUG test.cu

This is the backtrace: https://gist.github.com/dachziegel/0e5d955e2df30179f2b1

My setup:
GTX 680
64bit Linux
GCC 4.8.2
CUDA 6.0

**Comment by jaredhoberock** [comment] 2015-03-02 19:55
Hi @dachziegel,

With which version of Thrust do you observe this behavior?

**Comment by dachziegel** [comment] 2015-03-02 21:14
I tried it with the latest git commit (c9761ba472cfd78780063c3b792438d632ca94f3).
But the bug probably exists in earlier commits as well.

**Comment by dachziegel** [comment] 2015-03-03 09:11
I found out that the program does fail when compiling for **sm_20** but does not fail for **sm_30**.
Is sm_20 still supported by thrust?

**Comment by jaredhoberock** [comment] 2015-03-03 22:08
I can't reproduce the behavior on my system. Could you try again with CUDA 6.5 or 7?

**Comment by dachziegel** [comment] 2015-03-04 06:01
Program does not fail for me when using CUDA 6.5, however it did take 7.44 minutes to compile (see #641).

**Comment by jaredhoberock** [comment] 2015-03-04 20:00
Thanks. I will assume the discrepancy is due to a compiler issue resolved in CUDA 6.5.

**Closed by jaredhoberock** 2015-03-04 20:00 UTC
