### ISSUE TITLE
CUDA 8.0 upgrade breaks CUDA 7.5 code using thrust libraries

### ISSUE THREAD

**Issue by isaacgerg** [thrust/thrust#799] opened 2016-05-27 22:22 UTC
Upgraded from CUDA 7.5 to 8.0.  None of my thrust code compiles now.

I am using visual studio 2013 on windows 7.

Missing type specifier in get_iterator_value.h, line 42
'tuple': unspecialized class template can't be used as a template argument for template parameter 'T'.... in tupl.inl, line 88

I get a few hundred of these errors repeated in my code.

**Comment by jaredhoberock** [comment] 2016-05-27 22:30
@egaburov Could you look into one? My guess is that `get_iterator_value.h` may be missing an `#include`.

**Comment by jaredhoberock** [comment] 2016-05-27 23:39
Just taking a look at the functionality used inside this header, it looks like the following `#include`s would be required:

  * `iterator_traits.h`
  * `execution_policy.h`
  * `pointer_traits.h`
  * `thrust/system/detail/generic/memory` (for `get_value()`)

Not sure if these particular errors are caused by these missing `#include`s.

**Comment by isaacgerg** [comment] 2016-05-28 00:35
Added the following and problem fixed.  Thanks!

#include <thrust/iterator/iterator_traits.h>
#include <thrust/execution_policy.h>
#include <thrust/system/detail/generic//memory.h>

**Comment by jaredhoberock** [comment] 2016-05-31 16:42
This should be fixed in 1.8.3 and master now.

**Closed by jaredhoberock** 2016-05-31 16:42 UTC
