### ISSUE TITLE
Another -dc device/host conflict with nvcc 10.1 + Thrust 1.9.4

### ISSUE THREAD

**Issue by hwinkler** [thrust/thrust#973] opened 2019-04-13 19:30 UTC
Compiling this code with the `-dc` option to `nvcc` causes a device/host conflict:

```
#include <thrust/iterator/discard_iterator.h>
#include <thrust/device_vector.h>
#include <thrust/reduce.h>

void foo()
{
    auto probs = thrust::device_vector<float>(10, 0);
    auto fineProbs = thrust::device_vector<float>(10, 0);
    auto fineCells = thrust::device_vector<int32_t>(10, 0);
    thrust::reduce_by_key(fineCells.begin(),
                          fineCells.end(),
                          fineProbs.begin(),
                          thrust::make_discard_iterator(),
                          probs.begin());
}
```

Command line is
```
/usr/lib/cuda-10.1/bin/nvcc  -dc -std=c++11 --generate-code=arch=compute_60,code=sm_60  bug.cu
```

The error message is:
```
/usr/lib/cuda-10.1/bin/../targets/x86_64-linux/include/thrust/system/cuda/detail/reduce_by_key.h(1029): error:
 calling a __host__ function("thrust::detail::aligned_reinterpret_cast<int *, void *> ") 
 from a __host__ __device__ function(
  "thrust::cuda_cub::__reduce_by_key::reduce_by_key< ::thrust::cuda_cub::tag,  
::thrust::detail::normal_iterator< ::thrust::device_ptr<int> > ,  ::thrust::detail::normal_iterator< 
::thrust::device_ptr<float> > ,  ::thrust::discard_iterator< ::thrust::use_default> ,  
::thrust::detail::normal_iterator< ::thrust::device_ptr<float> > ,  ::thrust::equal_to<int> ,  ::thrust::plus<float> > ") is not allowed


```

I've attached this code and a makefile. #924  and #935 seem related but were against earlier versions.

**Comment by hwinkler** [comment] 2019-04-13 19:31
[cubug.tar.gz](https://github.com/thrust/thrust/files/3076659/cubug.tar.gz)

**Comment by griwes** [comment] 2019-04-13 20:22
This is a duplicate of #949; the fix is in flight, should land on github next week.

**Comment by griwes** [comment] 2019-04-15 18:23
This should be fixed on `master` now.

**Closed by griwes** 2019-04-15 18:23 UTC
