### ISSUE TITLE
sporadic error: "after cub_::DeviceRadixSort::SortPairs(1): invalid argument"

### ISSUE THREAD

**Issue by dachziegel** [thrust/thrust#563] opened 2014-10-10 08:19 UTC
In my program the following error ocurrs only sporadically:

<pre>
after cub_::DeviceRadixSort::SortPairs(1): invalid argument
</pre>

I only found a reference to that error message in stable_radix_sort.inl, so probably the thrust::sort_by_key in my program is causing this.
Since this error only occurs very infrequently, it is very hard to gain any more insights.
Do you have any clue what could be the cause of this problem? Any idea on how to debug this?

---

latest thrust from github
CUDA 6.0
Ubuntu 14.04 (x64)
gcc 4.8.2
NVIDIA Driver 343.22
NVIDIA GTX 680

**Comment by jvalenciag** [comment] 2015-11-08 00:18
Same problem here when I try to sort a vector of size > 1.5GB
Cuda 7.0
Ubuntu 14.04 (x64)
gcc 4.8.4
Tesla K40c

**Comment by renbozqin** [comment] 2016-10-20 03:26
Same problem.
Cuda 7.5
Centos7.0 (x64)
gcc 4.8.4
gtx Titan X

**Comment by egaburov** [comment] 2016-10-21 19:14
What is the compilation line. Make sure you pass at least -arch=sm_30. Kepler+ support block sizes > 65535

**Comment by aliyekta** [comment] 2016-10-21 19:24
Thanks, I did not have arch in the compile line,  this solved my issue with the call and it no longer gives an error.
Thanks

**Comment by dachziegel** [comment] 2016-10-22 11:53
@egaburov does this mean thrust only supports sm_30 and up?

**Comment by Dredok** [comment] 2016-11-17 17:03
same problem here.
I have tested this on a GTX 1070 and a K2200, in windows 10 vs2013 x64. 
I use CUDA 8.0, compile support for 30, 50 and 61.

I have reproduced this bug in a fairly complex code, with lots of libraries. Everything runs smoothly until I make a call to a library which uses constant memory, after calling this library I can not call thrust::sort_by_key because it will produce this error. 
I will try to isolate the code and fill a bug

**Comment by jbedorf** [comment] 2017-01-24 14:28
I saw this error as well, but it turned out to be caused in a completely different part of my own code. 
In case anyone runs into this, this happened for me:
An invalid value was set using cudaDeviceSetLimit. The return value of this function was not checked and hence the error got unnoticed. Follow up function and kernel calls did have their error codes checked, but progressed fine. 
The error only surfaced inside the Thrust/cub code,  because it uses the 'cudaPeekAtLastError' function which made the 'invalid argument' error surface again.

**Comment by mcfatealan** [comment] 2017-06-27 03:04
Met this issue. Found that it's due to '-g' flag when compiling. After removing it, everything is okay.

**Comment by mcfatealan** [comment] 2017-07-02 02:09
Met this bug on Tesla K40M. The weird thing is that using "-arch=sm_35" does not solve this issue. After struggling with all the solutions I can come out (including switching to CUDPP library, later found that it used thrust too), I gave up. In the morning it suddenly stroke me that I should test "-arch=sm_30". Worked. Feeling wasted now.

**Comment by mcfatealan** [comment] 2017-07-02 02:48
reboot machine, now works

**Comment by brycelelbach** [comment] 2017-09-17 02:30
Is this still an issue?

**Comment by brycelelbach** [comment] 2017-10-23 19:16
Closing this for now. If it is still an issue, please reopen.

**Closed by brycelelbach** 2017-10-23 19:16 UTC
Labels: functional bug
