### ISSUE TITLE
Will thrust support partial sort?

### ISSUE THREAD

**Issue by cysin** [thrust/thrust#816] opened 2016-07-12 06:32 UTC
I need to find the top k values in an array(first k smallest or largest values), so will thrust support partial sort?

**Comment by cbezault** [comment] 2016-07-14 23:07
I don't think so. See isssue #75.

**Comment by egaburov** [comment] 2016-07-14 23:51
Would nth_element [1] be sufficient for your purpose?

[1] http://en.cppreference.com/w/cpp/algorithm/nth_element

**Comment by brycelelbach** [comment] 2017-10-13 07:03
Duplicate of #75. Closing.

Hopefully someday!

**Closed by brycelelbach** 2017-10-13 07:03 UTC
Labels: duplicate, enhancement
