### ISSUE TITLE
Strict aliasing violation in scan_with_buffer

### ISSUE THREAD

**Issue by jlebar** [thrust/thrust#815] opened 2016-07-08 22:42 UTC
https://github.com/thrust/thrust/blob/25669cd425a8f4d896e4a631683899e55086f733/thrust/system/cuda/detail/bulk/algorithm/scan.hpp#L357

If `input_type` and `intermediate_type` are not the same, a C++ compiler can assume that a pointer of type `input_type*` does not alias a pointer of type `intermediate_type*`.  Yet here they clearly do alias when we invoke scan() below.

This can lead to all sorts of difficult-to-track-down bugs.

**Comment by brycelelbach** [comment] 2017-09-15 23:55
We've switched to a new implementation for the CUDA backend. Amusingly, there is another union problem in the new backend, but I'm pretty sure this is no longer an issue. Leaving it open until I can confirm. Also, hi Justin.

**Comment by jlebar** [comment] 2017-09-15 23:58
Hi, Bryce.  :)

> We've switched to a new implementation for the CUDA backend. 

Hm, I'm not sure what you mean.

I was referring to the fact that this code can miscompile if you compile with clang.

**Comment by brycelelbach** [comment] 2017-09-16 00:12
Sorry: what I meant is that this is likely no longer an issue, because the code in question has been rewritten in the CUDA toolkit version of Thrust.

**Comment by andrewcorrigan** [comment] 2017-09-16 13:54
Is the CUDA toolkit version of Thrust open-source?  Are you going to merge the github repository with the CUDA toolkit version?

**Comment by brycelelbach** [comment] 2017-09-17 02:19
Yes, the version of CUDA that ships with Thrust is open source.

I don't have an answer for the second question right now.

**Comment by brycelelbach** [comment] 2017-10-13 07:04
Closing; this is no longer an issue, although there are other places where unions may be abused.

**Closed by brycelelbach** 2017-10-13 07:04 UTC
Labels: functional bug, unverified
