### ISSUE TITLE
Cannot compile the OpenMP implementation of device_vector.h

### ISSUE THREAD

**Issue by vicp74** [thrust/thrust#977] opened 2019-04-24 01:02 UTC
Compiling a code which includes `<thrust/device_vector.h>` fails when using the OpenMP implementation.

The error can be reproduced by compiling example `basic_vector.cu` with

    g++ -DTHRUST_DEVICE_SYSTEM=THRUST_DEVICE_SYSTEM_OMP -x c++ minimal_example.cu -I/opt/cuda/include -L/opt/cuda/lib64

which throws

    In file included from /opt/cuda/include/thrust/device_allocator.h:27,
                 from /opt/cuda/include/thrust/device_vector.h:26,
                 from minimal_example.cu:1:
    /opt/cuda/include/thrust/memory/detail/device_system_resource.h:34:59: error: 'universal_host_pinned_memory_resource' in namespace 'thrust::system::omp' does not name a type
     typedef thrust::system::__THRUST_DEVICE_SYSTEM_NAMESPACE::universal_host_pinned_memory_resource
                                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /opt/cuda/include/thrust/memory/detail/device_system_resource.h:34:9: note: suggested alternative: 'host_pinned_memory_resource'
     typedef thrust::system::__THRUST_DEVICE_SYSTEM_NAMESPACE::universal_host_pinned_memory_resource
         ^~~~~~
         host_pinned_memory_resource

However, compiling with nvcc works fine. I'm using CUDA 10.1 and gcc 8.3.

**Comment by griwes** [comment] 2019-04-24 12:16
This is a duplicate of #962. Sorry for that!

**Closed by griwes** 2019-04-24 12:16 UTC
